parameters:
- name: gitUsername
  type: string
  default: AishwaryaaRaghuraman
- name: repoName
  type: string
  default: azure
- name: branchName
  type: string
  default: main


trigger:
- main

variables: 
  pythonVersion: '3.7'

jobs:
- job: Build 
  displayName: 'Build Python Application'
  pool: Default
 
  steps:
  - script: echo "Git Clone"
    displayName: 'Git Clone'
    env:
      GIT_USERNAME: $(gitUsername)
      REPO_NAME: $(repoName)
      BRANCH_NAME: $(branchName)
    continueOnError: false

  - script: |
      echo "Running SonarQube Scan"
      sonar-scanner.bat -D"sonar.projectKey=$(projectkey)" -D"sonar.sources=." -D"sonar.host.url=$(SONAR_URL)" -D"sonar.token=$(SONAR_TOKEN)" 
    displayName: 'Run SonarQube Scanning'

  - script: |
      echo Starting the build
      cd hello-python-master/app/
      python --version
      python -m venv venv
      .\venv\Scripts\activate 
      pip install -r requirements.txt
      python main.py
    displayName: 'Build with Python'
    

    # - task: PublishPipelineArtifact@1
    #   inputs:
    #     targetPath: '$(Pipeline.Workspace)'
    #     artifact: 'build-artifact'
    #     publishLocation: 'pipeline'
    
  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
            rootFolderOrFile: '$(projectRoot)'
            includeRootFolder: false
            archiveType: zip
            archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            replaceExistingArchive: true
            
  - task: PublishBuildArtifacts@1
    inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          artifactName: Python

